version: '3.7'
services:

  monty-backend:
    build:
      context: ./monty
    container_name: monty-backend
    networks:
    - monty
    - postgres-local
    environment:
      LOG_LEVEL: DEBUG
      POSTGRES_HOST: postgres-local
      POSTGRES_PASSWORD: monty-dev
      JWT_SECRET: qJNJvkW2uVWtuPjN

  monty-frontend:
    build:
      context: ./frontend
    container_name: monty-frontend
    networks:
    - monty

  monty-identity-provider:
    build:
      context: ./identity_provider
    container_name: identity-provider
    networks:
    - monty
    - postgres-local
    environment:
      LOG_LEVEL: DEBUG
      POSTGRES_HOST: postgres-local
      POSTGRES_PASSWORD: monty-dev
      JWT_SECRET: qJNJvkW2uVWtuPjN
      JWT_EXPIRY: 180

  monty-login:
    build:
      context: ./login
    container_name: monty-login
    networks:
    - monty

  reverse-proxy:
    build:
      context: ./reverse_proxy
    container_name: reverse-proxy
    ports:
    - "8081:8080"
    networks:
    - monty
    environment:
      LOG_LEVEL: DEBUG

networks:
  monty:
    name: monty
  postgres-local:
    name: postgres-local