version: '3.7'
services:

  monty-server:
    build:
      context: ./monty
    container_name: monty
    networks:
    - monty
    - postgres-local
    environment:
      LOG_LEVEL: DEBUG
      POSTGRES_HOST: postgres-local
      POSTGRES_PASSWORD: monty-dev
      JWT_SECRET: qJNJvkW2uVWtuPjN
      JWT_EXPIRY: 180

  monty-identity-provider:
    build:
      context: ./identity_provider
    container_name: identity_provider
    networks:
    - monty
    - postgres-local
    environment:
      LOG_LEVEL: DEBUG
      POSTGRES_HOST: postgres-local
      POSTGRES_PASSWORD: monty-dev
      JWT_SECRET: qJNJvkW2uVWtuPjN

  reverse-proxy:
    build:
      context: ./reverse_proxy
    container_name: reverse_proxy
    ports:
    - "8081:8080"
    networks:
    - monty
    environment:
      LOG_LEVEL: DEBUG

networks:
  monty:
    name: monty
  postgres-local:
    name: postgres-local