version: '3.7'
services:

  monty-backend:
    build:
      context: ./monty
    container_name: monty-backend
    networks:
    - monty
    - postgres
    - core
    env_file:
    - .env

  monty-frontend:
    build:
      context: ./frontend
    container_name: monty-frontend
    networks:
    - monty
    - core

networks:
  monty:
    name: monty
  core:
    name: core
  postgres:
    name: postgres